ams/PoolTestEnvironment/urls.py
from django.urls import path
from PoolTestEnvironment.views import *

app_name = 'pool-test-environment'

urlpatterns = [
    path('api/bookings/', BookingList.as_view(), name='booking-list'),
    path('api/booking/', BookingAPIView.as_view(), name='create-booking'),
    path('api/booking/<str:namespace>/', BookingAPIView.as_view(), name='update-booking'),
    path('api/namespaces/', NamespaceList.as_view(), name='namespace-list'),
    path('pool-deployments/', NamespaceTableView.as_view(), name='pool-data'),
    path('pool-deployments/booking-requests', BookingRequestsTableView.as_view(), name='booking-requests'),
    path('pool-deployments/trigger_jenkins/', TriggerJenkinsView.as_view(), name='trigger-jenkins'),
    path('pool-deployments/my-environments/', MyPoolEnvironmentsView.as_view(), name='my-pool-environments'),
    path('pool-deployments/my-environments/order', RequestEnvironmentView.as_view(), name='request-pool-environment'),
    path('pool-deployments/booking/update/<int:pk>/', BookingUpdateView.as_view(), name='pool-booking-update'),
    path('pool-deployments/booking-requests/update/<int:pk>/', AssignNamespaceToBookingView.as_view(), name='assign-namespace-to-booking'),
]

ams/ams/urls.py
from statistics import mode
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls')),
    path('', include("home.urls")),
    path('', include("manager.urls")),
    path('api/', include("managerapi.urls")),
    path('', include("PoolTestEnvironment.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ams/authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

ams/manager/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'manager'

urlpatterns = [
    path('my-profile', views.my_profile, name='my_profile'),
    path('account/list', views.account_list, name='accounts_list'),
    path('account/remove', views.account_remove, name='account_remove'),
    path('account/remove_enm', views.account_remove_enm, name='account_remove_enm'),
    path('account/remove_eo', views.account_remove_eo, name='account_remove_eo'),
    path('account/remove_eic', views.account_remove_eic, name='account_remove_eic'),
    path('account/<account_name>/details', views.account_details, name='account_details'),
    path('account/order', views.AddOrderView.as_view(), name='account_order'),
    path('account/add', views.AddAccountView.as_view(), name='account_add'),
    path('area/add', views.area_add, name='area_add'),
    path('area/<area_name>/manage', views.area_manage, name='area_manage'),
    path('area/list', views.area_list, name='area_list'),
    path('area/<area_name>/details', views.area_details, name='area_details'),
    path('area/remove', views.area_remove, name='area_remove'),
    path('system/remove', views.system_remove, name='system_remove'),
    path('system/list', views.system_list, name='systems_list'),
    path('system/add', views.system_add, name='system_add'),
    path('system/<system_name>/manage', views.system_manage, name='system_manage'),
    path('system/<system_name>/send_email', views.system_email_send, name='system_email_send'),
    path('system/<system_name>/set_status', views.system_status_set, name='system_status_set'),
    path('system/<system_name>/clear_status', views.system_status_clear, name='system_status_clear'),
    path('system/<system_name>/details', views.system_details, name='system_details'),
    path('order/list', views.jira_list, name='orders_list'),
    path('order/<order_id>/details', views.order_details, name='order_details'),
    path('jira/<jira_id>/details', views.jira_details, name='jira_details'),
    path('order/manage', views.order_manage, name='order_manage'),
    path('order/accept', views.order_accept, name='order_accept'),
    path('order/decline', views.order_decline, name='order_decline'),
    path('system-type/list', views.system_type_list, name='system_type_list'),
    path('system-type/add', views.system_type_add, name='system_type_add'),
    path('system-type/user_profile_remove_enm', views.user_profile_remove_enm, name='user_profile_remove_enm'),
    path('system-type/user_profile_remove_eo', views.user_profile_remove_eo, name='user_profile_remove_eo'),
    path('system-type/user_profile_remove_eic', views.user_profile_remove_eic, name='user_profile_remove_eic'),
    path('system-type/<system_type_name>/details', views.system_type_details, name='system_type_details'),
    path('system-type/<system_type_name>/add_profile', views.user_profile_add, name='user_profile_add'),
    path('system-type/<system_type_name>/add_role', views.user_role_add, name='user_role_add'),
    path('system-type/<system_type_name>/manage', views.system_type_manage, name='system_type_manage'),
    path('system-type/<system_type_group_name>/<profile_name>/manage', views.user_profile_manage, name='user_profile_manage'),
    path('system-type/<system_type_group_name>/<profile_name>/details', views.user_profile_details, name='user_profile_details'),
    path('system-type/remove', views.system_type_remove, name='system_type_remove'),
    path('approver/list', views.approver_list, name='approver_list'),
    path('approver/<approver_name>/manage', views.approver_manage, name='approver_manage'),
    path('approver/add', views.approver_add, name='approver_add'),
    path('approver/<approver_name>/details', views.approver_details, name='approver_details'),
    path('reset/<account_id>/<system_name>',views.reset_enmpassword,name='reset_enmpassword'),
    path('access-denied/', views.access_denied, name='access_denied'),
    path('jira-failed/', views.jira_failed, name='jira_failed'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ams/templates/booking-requests.html
{% extends 'base.layout.tmpl.html' %}
{% load django_tables2 %}



{% block "navi-bar" %}
      <nav class="appbar">
        <div class="actions-left">
          <div class="item">
            <i class="navigation-toggle closed"></i>
          </div>
          <div class="menu-anchor open-menu">Menu</div>
          <div class="title open-menu">
            <span class="title-name">AMS</span>
            <span class="subtitle">Pool Booking Requests</span>
          </div>
        </div>
        <div class="actions-right"></div>
      </nav>
{% endblock %}

{% block  "navigation" %}
  <li><a class="item" href="/">Home</a></li>
  <li><a class="item " href="/about">About</a></li>
  {% if user.is_authenticated %}
  <li><a class="item" href="{% url 'manager:my_profile' %}">My Profile</a></li>
  <li>
    <span class="title closed item">Accounts</span>
      <ul>
        <li><a class="item active" href="{% url 'manager:accounts_list' %}" id="accounts" class="item">List</a></li>
        <li><a href="{% url 'manager:account_order' %}"class="item">Order</a></li>
        {% if user.is_operator %}
        <li><a href="{% url 'manager:account_add' %}"class="item">Add</a></li>
        {% endif %}
      </ul>
  </li>
  <li>
    <span class="title closed item">Systems</span>
      <ul>
        <li><a href="{% url 'manager:systems_list' %}" class="item">List</a></li>
        {% if user.is_operator %}
        <li><a href="{% url 'manager:system_add' %}"class="item">Add</a></li>
        {% endif %}
      </ul>
  </li>
  
  <li>
    <span class="title closed item">Orders</span>
      <ul>
        <li><a href="{% url 'manager:orders_list' %}" class="item">List</a></li>
        {% if user.is_approver or user.is_operator %}
        <li><a href="{% url 'manager:order_manage' %}"class="item">Pending Approvals</a></li>
        {% endif %}
      </ul>
  </li>
  {% if user.is_pool_user or user.is_pool_admin %}
  <li>
    <span class="title closed item">Pool Environments</span>
      <ul>
        {% if user.is_pool_admin %}
          <li><a href="{% url 'pool-test-environment:pool-data' %}" class="item">List</a></li>
          <li><a href="{% url 'pool-test-environment:booking-requests' %}" class="item">Booking Requests</a></li>
        {% endif %}
        <li><a href="{% url 'pool-test-environment:my-pool-environments' %}" class="item">My Pool Environments</a></li>
        <li><a href="{% url 'pool-test-environment:request-pool-environment' %}" class="item">Request Environment</a></li>
      </ul>
  </li>
  {% endif %}
  
  {% if user.is_adminstrator %}
  <li>
    <span class="title closed item">Admin Panel</span>
      <ul>
        <li><a href="{% url 'manager:area_list' %}"class="item">Manage Areas</a></li>
        <li><a href="{% url 'manager:system_type_list' %}"class="item">Manage System Types</a></li>
        <li><a href="{% url 'manager:approver_list' %}"class="item">Manage Approvers</a></li>
      </ul>
  </li>
  {% endif %}
  
  {% endif %}
{% endblock %}

{% block "content" %}

<!-- Test Filter Accordion
 -->

 {% if user.is_pool_admin %}
  <div class="row" style="overflow: auto;">
    <div class="col-md-12">
      <h2>Booking Requests - To be Approved By Team Muon</h2>
      {% render_table table %}
    </div>
  </div>
 {% endif %}

{% endblock %}



{% block "js" %}


  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>

    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
              var cookie = cookies[i].trim();
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');
    
    //Test for non-redirect trigger
    document.querySelectorAll('.table-container .item').forEach(item => {
      item.addEventListener('click', function() {
        var id = this.parentNode.parentNode.dataset.id;
        var name = this.parentNode.parentNode.dataset.name;
        var action = this.textContent.trim().toLowerCase().replace(' ', '-');
        var confirmed = confirm(`Are you sure you want to ${action} for namespace ${name}?`);
        if (confirmed) {
            fetch(`/pool-deployments/trigger_jenkins/`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken
                },
                body: JSON.stringify({
                    name: name,
                    namespace_id: id,
                    action: action
                })
            }).then(response => {
                console.log('Raw response:', response);
                return response.json();
            }).then(data => {
                console.log('Data from server:', data);
                console.log('data status is:',data.status)
                if (data.status === 'redirect') {
                    window.location.href = data.redirect_url;
                } else {
                    console.log(data);
                }
            }).catch(error => {
                console.error('Error:', error);
            });
        }
      });
    });
    

  </script>
    
{% endblock %}

ams/templates/jira-list.page.tmpl.html
{% extends 'base.layout.tmpl.html' %}
{% load render_table from django_tables2 %} 
{% load widget_tweaks %} 

{% block "navi-bar" %}
      <nav class="appbar">
        <div class="actions-left">
          <div class="item">
            <i class="navigation-toggle closed"></i>
          </div>
          <div class="menu-anchor open-menu">Menu</div>
          <div class="title open-menu">
            <span class="title-name">AMS</span>
            <span class="subtitle">Orders</span>
          </div>
        </div>
        <div class="actions-right"></div>
      </nav>
{% endblock %}


{% block  "navigation" %}
  <li><a class="item" href="/">Home</a></li>
  <li><a class="item " href="/about">About</a></li>
                {% if user.is_authenticated %}
                <li><a class="item" href="{% url 'manager:my_profile' %}">My Profile</a></li>
              <li>
                <span class="title closeded item">Accounts</span>
                  <ul>
                    <li><a href="{% url 'manager:accounts_list' %}" id="accounts" class="item">List</a></li>
                    <li><a href="{% url 'manager:account_order' %}"class="item">Order</a></li>
                    {% if user.is_operator %}
                    <li><a href="{% url 'manager:account_add' %}"class="item">Add</a></li>
                    {% endif %}
                  </ul>
              </li>
              <li>
                <span class="title closed item">Systems</span>
                  <ul>
                    <li><a class="item" href="{% url 'manager:systems_list' %}" class="item">List</a></li>
                    {% if user.is_operator %}
                    <li><a href="{% url 'manager:system_add' %}"class="item">Add</a></li>
                    {% endif %}
                  </ul>
              </li>
              
              <li>
                <span class="title opened item">Orders</span>
                  <ul>
                    <li><a class="item active" href="{% url 'manager:orders_list' %}" class="item">List</a></li>
                    {% if user.is_approver or user.is_operator %}
                    <li><a href="{% url 'manager:order_manage' %}"class="item">Pending Approvals</a></li>
                    {% endif %}
                  </ul>
              </li>
              
              {% if user.is_adminstrator %}
              <li>
                <span class="title closed item">Admin Panel</span>
                  <ul>
                    <li><a href="{% url 'manager:area_list' %}"class="item">Manage Areas</a></li>
                    <li><a href="{% url 'manager:system_type_list' %}"class="item">Manage System Types</a></li>
                    <li><a href="{% url 'manager:approver_list' %}"class="item">Manage Approvers</a></li>
                  </ul>
              </li>
              {% endif %}
              {% endif %}
{% endblock %}

{% block "content" %}
 <!-- Application: Content -->
        <div class="appcontent">

            <!-- Tile 1 -->
            <div class="tile sm-12">
              <div class="header">
                <div class="left">
                  <div class="title">{{ title1}}</div>
                  <div class="subtitle">{{ subtitle1 }}</div> 
                </div>
              </div>
              <div class="content">
              <br><br>


              <!--filter-->
              <div class="accordion lines">
                <ul>
                  <li tabindex="0">
                    <div class="title" allin>Filters<i class="icon icon-filter"></i></div>
                    <form id="tableForm"  method="POST" action="{% url 'manager:order_accept' %}">
                      {% csrf_token %}
  
                      {% include 'accept-dialog-page.tmpl.html' %}
                    </form>
                    <form id="tableForm"  method="POST" action="{% url 'manager:order_decline' %}">
                      {% csrf_token %}
  
                      {% include 'decline-dialog-page.tmpl.html' %}
                    </form>
                      
                    <div class="content">
                      <form method="get" class="eds-filter horizontal">
                        <div class="filter-body">
                          <div class="filter-group">
                          {% for field in orderFilter.form %}
                      
                            <div class="filter-element">
                              <label for="{{ field.auto_id }}">{{ field.label }}</label>  
                              {{ field }}                                     

                            </div>
                
                          {% endfor %}
                          </div>
                    
                          <div class="filter-footer">
                            <a href="{% url 'manager:orders_list' %}" class="btn">Reset Filter</a>
                            <button type="submit" class="btn primary">Filter</button>
                          </div>  
                        </div>
                      </form>
                    </div>
                  </li>
                </ul>
              </div>
                <!-- END OF FILTER-->
                  {% render_table orderTable %}

              </div>
            </div>
        </div>
{% endblock %}

{% block "js" %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  
const dialogAcceptDOM = document.getElementById('accept-dialog');
const dialogDeclineDOM = document.getElementById('decline-dialog');
const dialogAcceptButtons = document.querySelectorAll('button.accept-button');
const dialogDeclineButtons = document.querySelectorAll('button.decline-button');
const multiButtonAcccept = document.getElementById('accept-warning');
const multiButtonDecline = document.getElementById('decline-warning');

    $(document).ready(function() {
        $('input[type="checkbox"]').on('change', function() {
            var selectedRows = [];
            var selectedColumnValues = [];
            $('input[type="checkbox"]:checked').each(function() {
                selectedRows.push($(this).val());
                columnValue = $(this).closest('tr').find('td:nth(1)').text() + " on " + $(this).closest('tr').find('td:nth(6)').text() ;
                selectedColumnValues.push(columnValue);
            });
            $('#selected-rows-a').val(selectedRows.join(','));
            $('#selected-names-a').val(selectedColumnValues.join(','));
            var selectedDataText = selectedColumnValues.join(', ');
            $('#selectedData-a').text(selectedDataText);
            $('#selected-rows-d').val(selectedRows.join(','));
            $('#selected-names-d').val(selectedColumnValues.join(','));
            var selectedDataText = selectedColumnValues.join(', ');
            $('#selectedData-d').text(selectedDataText);
            
        });
    });

    const dialogAccept = new eds.Dialog(dialogAcceptDOM);
    const dialogDecline = new eds.Dialog(dialogDeclineDOM);
    dialogAccept.init();
    dialogAcceptButtons.forEach(button => {
      console.log("For each button");
      button.addEventListener('click', () => {
        $('#selected-rows-a').val(button.value);
        $('#selected-names-a').val(button.name);
        $('#selectedData-a').text(button.name);
        dialogAccept.show();
      });
    });

    dialogDecline.init();
    dialogDeclineButtons.forEach(button => {
      console.log("For each button");
      button.addEventListener('click', () => {
        $('#selected-rows-d').val(button.value);
        $('#selected-names-d').val(button.name);
        $('#selectedData-d').text(button.name);
        dialogDecline.show();
      });
    });

    dialogDOM.querySelector('button.warning').addEventListener('click', () => {
      dialog.hide();
    });

</script>


{% endblock %}

ams/templates/my-pool-environments-actions.html
<div class="dropdown" data-type="click" data-id="{{ record.id }}" data-name="{{ record.name }}">
    <button class="btn clickable primary">Actions</button>
    <div class="menu">
      <div class="item">Request Extension</div>
      <div class="item">Terminate Booking</div>
      <div class="item">Request Support</div>
    </div>
</div>

ams/templates/my-pool-environments-test.html
{% extends 'base.layout.tmpl.html' %}
{% load django_tables2 %}



{% block "navi-bar" %}
      <nav class="appbar">
        <div class="actions-left">
          <div class="item">
            <i class="navigation-toggle open"></i>
          </div>
          <div class="menu-anchor open-menu">Menu</div>
          <div class="title open-menu">
            <span class="title-name">AMS</span>
            <span class="subtitle">My Pool Environments</span>
          </div>
        </div>
        <div class="actions-right"></div>
      </nav>
{% endblock %}

{% block  "navigation" %}
  <li><a class="item" href="/">Home</a></li>
  <li><a class="item " href="/about">About</a></li>
  {% if user.is_authenticated %}
  <li><a class="item" href="{% url 'manager:my_profile' %}">My Profile</a></li>
  <li>
    <span class="title closed item">Accounts</span>
      <ul>
        <li><a class="item active" href="{% url 'manager:accounts_list' %}" id="accounts" class="item">List</a></li>
        <li><a href="{% url 'manager:account_order' %}"class="item">Order</a></li>
        {% if user.is_operator %}
        <li><a href="{% url 'manager:account_add' %}"class="item">Add</a></li>
        {% endif %}
      </ul>
  </li>
  <li>
    <span class="title closed item">Systems</span>
      <ul>
        <li><a href="{% url 'manager:systems_list' %}" class="item">List</a></li>
        {% if user.is_operator %}
        <li><a href="{% url 'manager:system_add' %}"class="item">Add</a></li>
        {% endif %}
      </ul>
  </li>
  
  <li>
    <span class="title closed item">Orders</span>
      <ul>
        <li><a href="{% url 'manager:orders_list' %}" class="item">List</a></li>
        {% if user.is_approver or user.is_operator %}
        <li><a href="{% url 'manager:order_manage' %}"class="item">Pending Approvals</a></li>
        {% endif %}
      </ul>
  </li>
  {% if user.is_pool_user or user.is_pool_admin %}
  <li>
    <span class="title closed item">Pool Environments</span>
      <ul>
        {% if user.is_pool_admin %}
          <li><a href="{% url 'pool-test-environment:pool-data' %}" class="item">List</a></li>
          <li><a href="{% url 'pool-test-environment:booking-requests' %}" class="item">Booking Requests</a></li>
        {% endif %}
        <li><a href="{% url 'pool-test-environment:my-pool-environments' %}" class="item">My Pool Environments</a></li>
        <li><a href="{% url 'pool-test-environment:request-pool-environment' %}" class="item">Request Environment</a></li>
      </ul>
  </li>
  {% endif %}
  
  {% if user.is_adminstrator %}
  <li>
    <span class="title closed item">Admin Panel</span>
      <ul>
        <li><a href="{% url 'manager:area_list' %}"class="item">Manage Areas</a></li>
        <li><a href="{% url 'manager:system_type_list' %}"class="item">Manage System Types</a></li>
        <li><a href="{% url 'manager:approver_list' %}"class="item">Manage Approvers</a></li>
      </ul>
  </li>
  {% endif %}
  
  {% endif %}
{% endblock %}

{% block "content" %}

<!-- <div class="table-middle">
  

</div> -->

<!-- Test Filter Accordion
 -->

<div class="row" style="overflow: auto;">
  <div class="col-md-12">
    <a href="{% url 'pool-test-environment:request-pool-environment' %}" class="btn"><i class="icon icon-tasks"></i>Order Enviroment</a>
  </div>
  

  <!-- <div class="col-md-12"> -->
  <div>
    <br></br>
    <div class="tile sm-12" id="t-basic">

      <!-- Header -->
      <div class="header">
        <div class="left">
          <div class="title">Pool Environment </div>
          <div class="subtitle">Information</div>
        </div>
      </div>
    
      <!-- Content -->
      <div class="content">
        
        <div class="box">
          <p>Teams channel link - </p>
          <br> </br>
          <p>Some Other link - </p>
          {% if messages %}
          
          <ul class="messages">
              {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
          </ul>
          {% endif %}
          
        </div>
        <!-- End of your content -->
      </div>
    
    </div>

    {% if user.is_pool_user or user.is_pool_admin %}
      
      {% if table1.data %}
        <h2>Active Bookings Team - {{ table1.data.0.booking.team.name }}</h2>
        {% render_table table1 %}
      
      {% else %}
      <h2>No Active Bookings for Your Team - Order an Enviroment above</h2>
      {% endif %}

      {% if table2.data %}
        
        <h2>Open Bookings Requests Team - {{ table2.data.0.team.name }}</h2>
        {% render_table table2 %}
      
      {% else %}
      <h2>No Open Booking Requests for Your Team - Order an Enviroment above</h2>
      {% endif %}

    {% endif %}
   
  </div>














{% endblock %}


{% block "js" %}


  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>

    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
              var cookie = cookies[i].trim();
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');
    
    //Test for non-redirect trigger
    document.querySelectorAll('.table-container .item').forEach(item => {
      item.addEventListener('click', function() {
        var id = this.parentNode.parentNode.dataset.id;
        var name = this.parentNode.parentNode.dataset.name;
        var action = this.textContent.trim().toLowerCase().replace(' ', '-');
        var confirmed = confirm(`Are you sure you want to ${action} for namespace ${name}?`);
        if (confirmed) {
            fetch(`/pool-deployments/trigger_jenkins/`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken
                },
                body: JSON.stringify({
                    name: name,
                    namespace_id: id,
                    action: action
                })
            }).then(response => response.text())
            .then(data => {
                console.log(data);
            })
            .catch(error => {
                console.error('Error:', error);
            });
        }
      });
    });
    

  </script>
    
{% endblock %}

ams/templates/status-dialog-page.tmpl.html
<div class="dialog" data-trigger="#status-button" data-type="simple" id="status-dialog">
  <div class="content">
    <div class="top">
      <div class="title">This status message will be set for {{system.name}}</div>
    </div>
    <div class="body">
  
      <label for="id_message">Message:</label>
      <textarea name="message" required></textarea><br>
    </div>
    <div class="bottom">
      <a href="" class="btn" data-close="true">Cancel</a>
      <button type="submit" id="set_status" class="btn warning">Send</button>
    </div>
  </div>
</div>

ams/templates/system-type-add.page.tmpl.html
{% extends 'base.layout.tmpl.html' %}

{% block "navi-bar" %}
      <nav class="appbar">
        <div class="actions-left">
          <div class="item">
            <i class="navigation-toggle closed"></i>
          </div>
          <div class="menu-anchor open-menu">Menu</div>
          <div class="title open-menu">
            <span class="title-name">AMS</span>
            <span class="subtitle">System Types</span>
          </div>
        </div>
        <div class="actions-right"></div>
      </nav>
{% endblock %}


{% block  "navigation" %}
  <li><a class="item" href="/">Home</a></li>
  <li><a class="item" href="/about">About</a></li>
  {% if user.is_authenticated %}
  <li><a class="item" href="{% url 'manager:my_profile' %}">My Profile</a></li>
  <li>
    <span class="title closeded item">Accounts</span>
      <ul>
        <li><a href="{% url 'manager:accounts_list' %}" id="accounts" class="item">List</a></li>
        <li><a href="{% url 'manager:account_order' %}"class="item">Order</a></li>
        {% if user.is_operator %}
        <li><a href="{% url 'manager:account_add' %}"class="item">Add</a></li>
        {% endif %}
      </ul>
  </li>
  <li>
    <span class="title closed item">Systems</span>
      <ul>
        <li><a href="{% url 'manager:systems_list' %}" class="item">List</a></li>
        {% if user.is_operator %}
        <li><a href="{% url 'manager:system_add' %}"class="item">Add</a></li>
        {% endif %}
      </ul>
  </li>
  
  <li>
    <span class="title closed item">Orders</span>
      <ul>
        <li><a href="{% url 'manager:orders_list' %}" class="item">List</a></li>
        {% if user.is_approver or user.is_operator %}
        <li><a href="{% url 'manager:order_manage' %}"class="item">Pending Approvals</a></li>
        {% endif %}
      </ul>
  </li>
  
  {% if user.is_adminstrator %}
  <li>
    <span class="title opened item">Admin Panel</span>
      <ul>
        <li><a href="{% url 'manager:area_list' %}"class="item">Manage Areas</a></li>
        <li><a href="{% url 'manager:system_type_list' %}"class="item active">Manage System Types</a></li>
        <li><a href="{% url 'manager:approver_list' %}"class="item">Manage Approvers</a></li>
      </ul>
  </li>
  {% endif %}
  {% endif %}
{% endblock %}

{% block "content" %}
 <!-- Application: Content -->
        <div class="appcontent">
          <!-- Row 1 -->
          <div class="row">

            <!-- Tile 1 -->
            <div class="tile sm-12">
              <div class="header">
                <div class="left">
                  <div class="title">{{ title1}}</div>
                  <div class="subtitle">{{ subtitle1 }}</div> 
                </div>
              </div>
              <div class="content">
                <form class="eds-form" method="POST" action="{% url 'manager:system_type_add' %}" enctype="multipart/form-data">
                  <div class="form-header">
        
                    <p>Please provide following system type details</p>
                  </div>
                  <div class="column sm-12 md-12 lg-6">
                    <div class="row form-body">
                      <div class="form-group">
                        {% csrf_token %}
                        {{ form }}
                      </div>
                  </div>
                  <div class="column sm-12 md-12 lg-6">
                    <div class="form-footer">
                      <button type="button" class="btn"><a href="{% url 'manager:system_type_list' %}"class="item">Cancel</a></button>
                      <button type="submit" class="btn primary">Add</button>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

{% block js %}

{% endblock %}